services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ${MOUNT_HOME}/workspace/access_log_sampling/dev_tooling/nginx_logs:/var/log/nginx:tmpfs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  apache:
    image: httpd:latest
    container_name: apache
    ports:
      - "8082:80"
    volumes:
      - ${MOUNT_HOME}/workspace/access_log_sampling/dev_tooling/apache_logs:/usr/local/apache2/logs:tmpfs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  envoy:
    image: envoyproxy/envoy:v1.32.1
    container_name: envoy
    volumes:
      - ${MOUNT_HOME}/workspace/access_log_sampling/dev_tooling/envoy.yaml:/etc/envoy/envoy.yaml
      - ${MOUNT_HOME}/workspace/access_log_sampling/dev_tooling/envoy_logs:/var/log/envoy:tmpfs
    ports:
      - "8080:8080"
      - "9901:9901"  # Envoy Admin interface
    depends_on:
      - nginx
      - otel-collector

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  otel-collector:
    image: affirm-otelcol:0.0.10
    container_name: otel-collector
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: 512M

    ports:
      - "4317:4317"    # gRPC receiver for OTLP
      - "8888:8888"
      - "55680:55680"  # OpenTelemetry receiver for traces
    volumes:
      - ${MOUNT_HOME}/workspace/access_log_sampling/dev_tooling/otel-config.yaml:/etc/otel-config.yaml:cached
      - ${MOUNT_HOME}/workspace/access_log_sampling/dev_tooling/exclusions.txt:/etc/exclusions.txt:cached
      - ${MOUNT_HOME}/workspace/access_log_sampling/dev_tooling/otel_logs:/var/log/otel-logs:tmpfs
    command: ["--config", "/etc/otel-config.yaml"]
    env_file:
      - ../.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    depends_on:
      kafka:
        condition: service_healthy

networks:
  network1:
    name: host
    external: true
