receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
  volumebasedlogsampler:
    sampling_rate: 0.5

exporters:
  kafka:
    brokers: ["kafka:9092"]
    topic: otel-logs
  debug:

service:
  telemetry:
    metrics:
      address: '0.0.0.0:8888'
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch, volumebasedlogsampler]
      exporters: [kafka, debug]
