dist:
  module: go.opentelemetry.io/collector/cmd/affirm-otelcol
  name: affirm-otelcol
  description: OTEL collector with custom components developped at Affirm
  output_path: ./affirm-otelcol
  version: 0.0.1

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.119.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.119.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter v0.119.0

processors:
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.119.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.119.0
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.119.0
  - gomod: volumebasedlogsampler v0.0.1
    path: "./volumebasedlogsampler"

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.119.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0
