receivers:
  otlp:
    protocols:
      grpc:

      http:  # This receiver supports health checks



processors:
  batch:  # Adds batching of data to reduce the number of outgoing requests
    timeout: 1s
    send_batch_size: 1024
  #probabilistic_sampler:
  #  sampling_percentage: 50
  #  attribute_source: record
  #  from_attribute: service
  #probabilistic_sampler/apache:
  #  sampling_percentage: 10
  #  attribute_source: record
  #  from_attribute: service
exporters:
  file:
    path: /var/log/otel-logs/otel-access-logs.json   # File exporter to save logs
    rotation:
      max_megabytes: 10
      max_backups: 5

  debug:
   # verbosity: detailed  # Console logging for debugging and verification
  otlp:
    endpoint: "host.docker.internal:4317"
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,file,otlp]
