dist:
  module: go.opentelemetry.io/collector/cmd/volumebasedsampler
  name: affirm-otelcol
  description: OTEL collector with custom components developped at Affirm
  output_path: ./affirm-otelcol
  version: 0.0.1

exporters:
  - gomod:
      # NOTE: Prior to v0.86.0 use the `loggingexporter` instead of `debugexporter`.
      go.opentelemetry.io/collector/exporter/debugexporter v0.115.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.115.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.115.0
  #- gomod:
  #    github.com/benjdauno/volumebasedlogsampler v0.1.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.115.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0
